In [100]:
import numpy as np

In [101]:
# inputs = np.array([[0,0],[0,1],[1,0],[1,1]])
# weights = np.array([0,0])
# outputs = np.array([[0],[1],[1],[0]])
# learning_rate = 0.1

In [102]:
inputs = np.array([[0,0],[0,1],[1,0],[1,1]])
outputs = np.array([[0],[1],[1],[0]])

weights0 = np.array([[-0.424,-0.740,-0.961],[0.358,-0.577,-0.469]])

weights1 = np.array([[-0.017],[-0.893],[0.148]])

learning_rate = 0.1

In [103]:
epochs = 100

In [104]:
def sigmoid(sum):
    return 1 / ( 1 + np.exp(-sum)) 


In [ ]:
def sigmoid_derivate(sigmoid):
    return sigmoid * (1-sigmoid)

In [ ]:
for epoch in epochs:
    

In [107]:
sum_synapse0 = np.dot(inputs,weights0)
sum_synapse0

array([[ 0.   ,  0.   ,  0.   ],
       [ 0.358, -0.577, -0.469],
       [-0.424, -0.74 , -0.961],
       [-0.066, -1.317, -1.43 ]])

In [109]:
hidden_layer = sigmoid(sum_synapse0)
hidden_layer

array([[0.5       , 0.5       , 0.5       ],
       [0.5885562 , 0.35962319, 0.38485296],
       [0.39555998, 0.32300414, 0.27667802],
       [0.48350599, 0.21131785, 0.19309868]])

In [112]:
sum_synapse1 = np.dot(hidden_layer,weights1)

In [113]:
output_layer = sigmoid(sum_synapse1)
output_layer

array([[0.40588573],
       [0.43187857],
       [0.43678536],
       [0.45801216]])

In [118]:
error_output_layer = np.mean(abs(outputs - output_layer))
error_output_layer

0.49880848923713045

In [99]:
calculate_output(np.array([0,1]))

0.5