In [13]:
import numpy as np

In [14]:
inputs = np.array([[0,0],[0,1],[1,0],[1,1]])
outputs = np.array([[0],[1],[1],[0]])

weights0 = np.array([[-0.424,-0.740,-0.961],[0.358,-0.577,-0.469]])

weights1 = np.array([[-0.017],[-0.893],[0.148]])

learning_rate = 0.1

In [15]:
epochs = 100

In [16]:
def sigmoid(sum):
    return 1 / ( 1 + np.exp(-sum)) 


In [17]:
def sigmoid_derivate(sigmoid):
    return sigmoid * (1-sigmoid)

In [18]:
# for epoch in epochs:
    

In [19]:
sum_synapse0 = np.dot(inputs,weights0)
sum_synapse0

array([[ 0.   ,  0.   ,  0.   ],
       [ 0.358, -0.577, -0.469],
       [-0.424, -0.74 , -0.961],
       [-0.066, -1.317, -1.43 ]])

In [20]:
hidden_layer = sigmoid(sum_synapse0)
hidden_layer

array([[0.5       , 0.5       , 0.5       ],
       [0.5885562 , 0.35962319, 0.38485296],
       [0.39555998, 0.32300414, 0.27667802],
       [0.48350599, 0.21131785, 0.19309868]])

In [21]:
sum_synapse1 = np.dot(hidden_layer,weights1)

In [22]:
output_layer = sigmoid(sum_synapse1)
output_layer

array([[0.40588573],
       [0.43187857],
       [0.43678536],
       [0.45801216]])

In [35]:
error_output_layer = outputs - output_layer
error_output_layer

array([[-0.40588573],
       [ 0.56812143],
       [ 0.56321464],
       [-0.45801216]])

In [31]:
derivative_ouputs =sigmoid_derivate(output_layer)
derivative_ouputs


array([[0.2411425 ],
       [0.24535947],
       [0.24600391],
       [0.24823702]])

In [37]:
error_output_layer

array([[-0.40588573],
       [ 0.56812143],
       [ 0.56321464],
       [-0.45801216]])

In [39]:
delta_output = error_output_layer* derivative_ouputs
delta_output

array([[-0.0978763 ],
       [ 0.13939397],
       [ 0.138553  ],
       [-0.11369557]])

In [45]:
delta_output_x_weights = delta_output.dot(weights1.T)
delta_output_x_weights

array([[ 0.0016639 ,  0.08740354, -0.01448569],
       [-0.0023697 , -0.12447882,  0.02063031],
       [-0.0023554 , -0.12372783,  0.02050584],
       [ 0.00193282,  0.10153015, -0.01682694]])